//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class user
    {
        public int Id { get; set; }
        [Required(ErrorMessage = "first name required")]
        [DisplayName("First Name")]
        public string firstName { get; set; }
        [DisplayName("Last Name")]
        [Required(ErrorMessage = "last name required")]
        public string lastName { get; set; }
        [DisplayName("Email")]
        [RegularExpression("^([0-9a-zA-Z]([-\\.\\w]*[0-9a-zA-Z])*@([0-9a-zA-Z][-\\w]*[0-9a-zA-Z]\\.)+[a-zA-Z]{2,9})$", ErrorMessage = "Invalid email")]
        public string email { get; set; }
        [DisplayName("User Name")]
        [Required(ErrorMessage = "user name required")]
        public string username { get; set; }
        [DisplayName("Password")]
        [Required(ErrorMessage = "password required")]
        //      [DataType(DataType.Password)]
        public string password { get; set; }
        [DisplayName("Conform Password")]
        [Required(ErrorMessage = "conform password required")]
        [Compare("password", ErrorMessage = "password not matched")]
   //     [DataType(DataType.Password)]
        public string conformpassword { get; set; }
    }
}
